### ISSUE TITLE
0.9.3 build failure on Debian Stretch and Ubuntu Bionic: ./tests/src/transformtest/transformtest.cpp:165: undefined reference to `bool QTest::qCompare<QString, char [19]>(QString const&, char const (&) [19], char const*, char const*, char const*, int)'

### ISSUE THREAD

**Issue by df7cb** [pgmodeler/pgmodeler#1504]
Building pgmodeler 0.9.3 on Debian Stretch (9) and Ubuntu Bionic (18.04) fails. This is not the same as #1486 but likely related to the compiler/library versions as well.

The 0.9.3-beta release was still fine so this is a post-beta regression.

This prevents the packages on apt.postgresql.org to be updated.

```
15:59:43 g++ -Wl,-rpath,'$ORIGIN' -Wl,-rpath,'$ORIGIN/../lib/pgmodeler' -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,--as-needed -o transformtest obj/transformtest.o   -L/<<PKGBUILDDIR>>/tests/src/transformtest/../../../libpgmodeler_ui/ -lpgmodeler_ui -L/<<PKGBUILDDIR>>/tests/src/transformtest/../../../libobjrenderer/ -lobjrenderer -L/<<PKGBUILDDIR>>/tests/src/transformtest/../../../libpgconnector/ -lpgconnector -L/<<PKGBUILDDIR>>/tests/src/transformtest/../../../libpgmodeler/ -lpgmodeler -L/<<PKGBUILDDIR>>/tests/src/transformtest/../../../libparsers/ -lparsers -L/<<PKGBUILDDIR>>/tests/src/transformtest/../../../libutils/ -lutils -lpq -lxml2 -lQt5PrintSupport -lQt5Svg -lQt5Widgets -lQt5Gui -lQt5Network -lQt5Test -lQt5Core -lGL -lpthread -lXext -lX11 -lm
15:59:47 obj/transformtest.o: In function `TransformTest::generatesNameAndSignatureCorrectly()':
15:59:47 ./tests/src/transformtest/transformtest.cpp:165: undefined reference to `bool QTest::qCompare<QString, char [19]>(QString const&, char const (&) [19], char const*, char const*, char const*, int)'
15:59:47 ./tests/src/transformtest/transformtest.cpp:166: undefined reference to `bool QTest::qCompare<QString, char [32]>(QString const&, char const (&) [32], char const*, char const*, char const*, int)'
15:59:47 ./tests/src/transformtest/transformtest.cpp:180: undefined reference to `bool QTest::qCompare<QString, char [16]>(QString const&, char const (&) [16], char const*, char const*, char const*, int)'
15:59:47 ./tests/src/transformtest/transformtest.cpp:181: undefined reference to `bool QTest::qCompare<QString, char [29]>(QString const&, char const (&) [29], char const*, char const*, char const*, int)'
15:59:47 ./tests/src/transformtest/transformtest.cpp:188: undefined reference to `bool QTest::qCompare<QString, char [33]>(QString const&, char const (&) [33], char const*, char const*, char const*, int)'
15:59:47 ./tests/src/transformtest/transformtest.cpp:189: undefined reference to `bool QTest::qCompare<QString, char [46]>(QString const&, char const (&) [46], char const*, char const*, char const*, int)'
15:59:47 collect2: error: ld returned 1 exit status
15:59:47 Makefile:150: recipe for target 'transformtest' failed
15:59:47 make[3]: *** [transformtest] Error 1
15:59:47 make[3]: Leaving directory '/<<PKGBUILDDIR>>/tests/src/transformtest'
```

Build logs:
https://pgdgbuild.dus.dg-i.net/job/pgmodeler-binaries/architecture=i386,distribution=stretch/20/console
https://pgdgbuild.dus.dg-i.net/job/pgmodeler-binaries/architecture=amd64,distribution=bionic/20/console

**Comment by rkhaotix** [comment]
Which Qt version?

**Comment by df7cb** [comment]
Debian:
not ok: qtbase5-dev | 5.7.1+dfsg-3+deb9u2    | oldstable    | amd64, arm64, armel, armhf, i386, mips, mips64el, mipsel, ppc64el, s390x
ok: qtbase5-dev | 5.11.3+dfsg1-1+deb10u4 | stable       | amd64, arm64, armel, armhf, i386, mips, mips64el, mipsel, ppc64el, s390x

Ubuntu:
not ok: qtbase5-dev | 5.9.5+dfsg-0ubuntu1    | bionic                    | amd64, arm64, armhf, i386, ppc64el, s390x
ok: qtbase5-dev | 5.12.8+dfsg-0ubuntu1   | focal/universe            | amd64, arm64, armhf, i386, ppc64el, riscv64, s390x

**Comment by rkhaotix** [comment]
pgModeler builds fine on Qt 5.9.9 to 5.15.1:

https://github.com/pgmodeler/pgmodeler/actions/runs/452673572

**Comment by df7cb** [comment]
(Updating the Qt version is out of scope.)

**Comment by df7cb** [comment]
Hi @rkhaotix: can I get a definite answer that you aren't supporting pgmodeler on these distributions anymore and that you want me to drop the packages from apt.postgresql.org?

**Comment by df7cb** [comment]
Also, https://www.pgmodeler.io/support/installation claims that Qt 5.9.x is supported.

**Comment by rkhaotix** [comment]
@df7cb I need to update the installation instructions but I will test once more the building on Qt 5.9.5. For Qt 5.7.x I don't have plans to keep supporting it.

**Comment by rkhaotix** [comment]
@df7cb It turns out that I forgot to include the tests in the building on GitHub CI. This is why the process was running ok.
I've tested locally and the build failed to Qt 5.9.5 to 5.9.9. So I fixed the broken tests and the build is now working fine.

But I still reinforce that I'll not make the building work for Qt 5.7.x since this is a pretty old version and Qt is famous to break compatibility between releases. So If I make changes to Qt 5.7.x maybe things will break in newer versions. :)
