### ISSUE TITLE
Error in building process

### ISSUE THREAD

**Issue by cameduar44** [pgmodeler/pgmodeler#1826]
**Bug description**
I've been trying to build and install pgModeler following the instructions on the official site, but keep having problems with the $make comand when I'm building the the software.

The problems seems to be at xmlparser.cpp library, especificly on line 182 xml_error=xmlGetLastError() cause when a run $make on MSYS this error massage appears:

src/xmlparser.cpp: In member function 'void XmlParser::readBuffer()':
src/xmlparser.cpp:182:42: error: invalid conversion from 'const xmlError*' {aka 'const _xmlError*'} to 'xmlError*' {aka '_xmlError*'} [-fpermissive]
  182 |                 xml_error=xmlGetLastError();
      |                           ~~~~~~~~~~~~~~~^~
      |                                          |
      |                                          const xmlError* {aka const _xmlError*}

**How to reproduce**
I've been looking in different forums but I couldn't find nothing similar. This happens everytime I run $make building the software 

**Info about your desktop**
 - OS: Windows 10 Pro
 - Version: 22H2
 - Window manager: 
 - pgModeler version: main
 - Qt version: 6

**Additional info**
I have no idea of C++

**Comment by jasparq** [comment]
I have the same issue. I tried using the 1.1.0 beta from the [source download form](https://pgmodeler.io/sourcecode), but the same error is thrown on a different line.

```
src/xmlparser.cpp: In member function 'void XmlParser::readBuffer()':
src/xmlparser.cpp:172:42: error: invalid conversion from 'const xmlError*' {aka 'const _xmlError*'}
to 'xmlError*' {aka '_xmlError*'} [-fpermissive]
  172 |                 xml_error=xmlGetLastError();
      |                           ~~~~~~~~~~~~~~~^~
      |                                          |
      |                                          const xmlError* {aka const _xmlError*}
make[2]: *** [Makefile.Release:768: obj/xmlparser.o] Error 1
make[2]: Leaving directory '/c/pgmodeler-1.1.0-beta/libs/libparsers'
make[1]: *** [Makefile:45: release] Error 2
make[1]: Leaving directory '/c/pgmodeler-1.1.0-beta/libs/libparsers'
make: *** [Makefile:102: sub-libs-libparsers-make_first-ordered] Error 2
```

**Comment by jasparq** [comment]
> It works with the 1.1.0-beta1 branch downloaded from [github](https://github.com/pgmodeler/pgmodeler/tree/1.1.0-beta1), not from the 1.1.0-beta tag (which is older and not fixed)...

Got it working. Thought they were the same, my mistake.

**Comment by damatvey** [comment]
How to switch to branch? I wrote the command  User@1B MINGW64 ~/pgmodeler
$ git checkout 1.1.0-beta1 
but did not switch to the specified branch

**Comment by rkhaotix** [comment]
Branch 1.1.0-beta1 was merged into develop branch after the release in December. You can try either checkout develop or 1.1.0.

**Comment by damatvey** [comment]
why is it that when I write this command
$ windeployqt-qt6 pgmodeler.exe gui.dll
"pgmodeler.exe" does not exist.
 It writes that pgmodeler.exe does not exist. Where could there be a mistake?

**Comment by damatvey** [comment]
@rkhaotix Thank you! You are really help me
